In [1]:
## laoding data set 


import pandas as pd

In [3]:
data= pd.read_csv("D:\python 2.0\placement.csv")

data.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [6]:
data= pd.read_csv("D:\python 2.0\placement.csv",index_col='cgpa')
data.head()

      Unnamed: 0     iq  placement
cgpa
6.8            0  123.0          1
5.9            1  106.0          0
5.3            2  121.0          0
7.4            3  132.0          1
5.8            4  142.0          0