In [1]:
import pandas as pd

In [3]:
data={"name":["abbas ","bilal","sulieman","gulali"],"age":[23,26,27,35],"sex":["male","male","male","female"]}

In [6]:

df=pd.DataFrame(data)

In [7]:
df

       name  age     sex
0    abbas    23    male
1     bilal   26    male
2  sulieman   27    male
3    gulali   35  female

In [8]:
df['age'].max()

np.int64(35)

In [10]:
df.describe()

             age
count   4.000000
mean   27.750000
std     5.123475
min    23.000000
25%    25.250000
50%    26.500000
75%    29.000000
max    35.000000

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   sex     4 non-null      str
dtypes: int64(1), str(2)
memory usage: 271.0 bytes

In [13]:
pd.Series([1,2,3,4,5,6,7,8,9],name="age")

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: age, dtype: int64

In [18]:
data={
    "shop":[20,40,150,44,444,5,4,5,67,7,8,9],
    "room_rent":[10,30,60,44,444,5,4,5,67,7,8,9],
    "food":[20,35,90,44,444,5,4,5,67,7,8,9],
    "revenve":[210,100,145,44,444,5,4,5,67,7,8,9],
    "data":["10-2-2012","10-2-2012","10-2-2012","10-2-2012","10-2-2012","10-2-2012","10-2-2012","10-2-2012","","10-2-2012","10-2-2012","10-2-2012",]
}

In [1]:
import pandas as pd

In [19]:
data_frame=pd.DataFrame(data)

In [20]:
data_frame

    shop  room_rent  food  revenve       data
0     20         10    20      210  10-2-2012
1     40         30    35      100  10-2-2012
2    150         60    90      145  10-2-2012
3     44         44    44       44  10-2-2012
4    444        444   444      444  10-2-2012
5      5          5     5        5  10-2-2012
6      4          4     4        4  10-2-2012
7      5          5     5        5  10-2-2012
8     67         67    67       67
9      7          7     7        7  10-2-2012
10     8          8     8        8  10-2-2012
11     9          9     9        9  10-2-2012

In [21]:
data_frame.head(3)

   shop  room_rent  food  revenve       data
0    20         10    20      210  10-2-2012
1    40         30    35      100  10-2-2012
2   150         60    90      145  10-2-2012

In [22]:
data_frame.tail(3)

    shop  room_rent  food  revenve       data
9      7          7     7        7  10-2-2012
10     8          8     8        8  10-2-2012
11     9          9     9        9  10-2-2012

In [23]:
data_frame.sample(4)

   shop  room_rent  food  revenve       data
4   444        444   444      444  10-2-2012
3    44         44    44       44  10-2-2012
9     7          7     7        7  10-2-2012
2   150         60    90      145  10-2-2012

In [24]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   shop       12 non-null     int64
 1   room_rent  12 non-null     int64
 2   food       12 non-null     int64
 3   revenve    12 non-null     int64
 4   data       12 non-null     str
dtypes: int64(4), str(1)
memory usage: 711.0 bytes

In [25]:
data_frame.describe()

             shop   room_rent        food     revenve
count   12.000000   12.000000   12.000000   12.000000
mean    66.916667   57.750000   61.500000   87.333333
std    125.982292  123.730003  123.641343  130.530619
min      4.000000    4.000000    4.000000    4.000000
25%      6.500000    6.500000    6.500000    6.500000
50%     14.500000    9.500000   14.500000   26.500000
75%     49.750000   48.000000   49.750000  111.250000
max    444.000000  444.000000  444.000000  444.000000

In [28]:
data_frame['room_rent']

0      10
1      30
2      60
3      44
4     444
5       5
6       4
7       5
8      67
9       7
10      8
11      9
Name: room_rent, dtype: int64

In [32]:
data_frame['room_rent'][data_frame['room_rent']>40]

2     60
3     44
4    444
8     67
Name: room_rent, dtype: int64